### PR TITLE
allow to not use requirements.txt, update docs, default for username

### PR DESCRIPTION
**Pull request by kopp**
Some small adaptions to improve usability.

### CODE REVIEW

**Comment by onichandame** [comment]
Thanks for your contribution!

**Comment by kopp** [comment]
welcome.  I just realized that you still need to supply the `username: __token__` because of `required: true`.  If you deem that useful, could you please change it (or I'll open a Pull Request with only this change if you like...)

**Comment by onichandame** [comment]
@kopp Oh, I thought that `default` option would overwrite the `required: true` option, just like the default function arguments making the argument optional in C++, TypeScript etc. Still have a lot to learn indeed.

As you are the author of this PR and you found the issue, I would prefer to have the changes signed by you. But if you won't bother, I will apply the patch with your name credited after 24 hours anyways.

**Comment by kopp** [comment]
Hm... Now that you say that... I'm using your action in
https://github.com/kopp/calliope-mini-stubs/blob/master/.github/workflows/deploy.yaml
but when running it for the first time, I got an error saying that I need to specify the password.  But I did not specify the `setup` script either but it worked.  It looks like the changes from this pull request were not included in the action (see e.g. https://github.com/kopp/calliope-mini-stubs/runs/812709361?check_suite_focus=true#step:4:81)  Probably this is because i use `@master` which is actually discouraged.  I'll use the `@tag` syntax and see what happens :)

**Comment by onichandame** [comment]
Sorry I didn't mention that the latest release 0.0.2 is available. `@0.0.2` has been tested and works as expected. [The marketplace](https://github.com/marketplace/actions/pip-upload) has the latest release available.

As for the `@master` in the README, I was just too lazy to update the version number for every release. Indeed we should check out a tag/commit instead of `master` in production.

On your previous suggestion about the `required: true` option, I re-checked the `action.yml` and found that all options are required. But in usage, I didn't notice any error when most of them are omitted. Therefore I guess that the options with default values are optional implicitly.

**Pull request merged**
